name: Build and Package CLI

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release

jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install cargo-bundle for Linux/macOS
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      run: cargo install cargo-bundle

    - name: Install cargo-wix for Windows
      if: matrix.os == 'windows-latest'
      run: cargo install cargo-wix

    - name: Package for Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        cargo bundle --release
        mkdir -p artifacts
        mv target/release/bundle/deb/*.deb artifacts/

    - name: Package for macOS
      if: matrix.os == 'macos-latest'
      run: |
        cargo bundle --release 
        mkdir -p artifacts
        mv target/release/bundle/osx/*.app artifacts/

    - name: Package for Windows
      if: matrix.os == 'windows-latest'
      run: |
        cargo wix init crates/cli/e2ee/Cargo.toml
        cargo wix
        mkdir -p artifacts
        mv target/*.msi artifacts/

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cli-artifacts-${{ matrix.os }}
        path: artifacts/
